# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f2f_url', models.CharField(default='', max_length=256)),
                ('title', models.CharField(default='', max_length=256)),
                ('source', models.CharField(default='', max_length=256)),
                ('recipe_id', models.IntegerField(default=0, unique=True)),
                ('image_url', models.CharField(default='', max_length=512)),
            ],
            options={
                'db_table': 'recipe_tbl',
            },
        ),
    ]
