# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'food_tbl',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=256)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='f2f_url',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='food.Ingredient', to='food.FoodItem'),
        ),
    ]
