# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20171004_2005'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient_tbl',
        ),
    ]
