# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20171004_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.FoodItem'),
        ),
    ]
