# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20171004_2046'),
        ('food', '0006_auto_20171005_2012'),
    ]

    operations = [
    ]
